### ISSUE TITLE
[Bug] Crashing while trying to open specific issue

### ISSUE THREAD

**Issue by KaKi87** [rejasupotaro/octodroid#6]
https://github.com/ForkIssues/Tracker/issues/562

```
time: 1579271989092 msg: com.squareup.moshi.JsonDataException: Expected one of [added_to_project, assigned, base_ref_changed, base_ref_force_pushed, closed, comment_deleted, commented, committed, converted_note_to_issue, cross-referenced, demilestoned, deployed, head_ref_deleted, head_ref_force_pushed, head_ref_restored, labeled, locked, marked_as_duplicate, mentioned, merged, moved_columns_in_project, milestoned, pinned, ready_for_review, referenced, removed_from_project, renamed, reopened, reviewed, review_dismissed, review_requested, review_request_removed, subscribed, transferred, unassigned, unlabeled, unlocked, unmarked_as_duplicate, unpinned, unsubscribed] but was user_blocked at path $.items[3].event stacktrace: io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47) 	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onError(ReactiveLoaders.java:51) 	at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:33) 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476) 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444) 	at android.support.v4.content.Loader.deliverResult(Loader.java:126) 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109) 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44) 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:85) 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:82) 	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:44) 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79) 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109) 	at android.os.Handler.handleCallback(Handler.java:883) 	at android.os.Handler.dispatchMessage(Handler.java:100) 	at android.os.Looper.loop(Looper.java:214) 	at android.app.ActivityThread.main(ActivityThread.java:7356) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) ComposedException 1 : 	com.squareup.moshi.JsonDataException: Expected one of [added_to_project, assigned, base_ref_changed, base_ref_force_pushed, closed, comment_deleted, commented, committed, converted_note_to_issue, cross-referenced, demilestoned, deployed, head_ref_deleted, head_ref_force_pushed, head_ref_restored, labeled, locked, marked_as_duplicate, mentioned, merged, moved_columns_in_project, milestoned, pinned, ready_for_review, referenced, removed_from_project, renamed, reopened, reviewed, review_dismissed, review_requested, review_request_removed, subscribed, transferred, unassigned, unlabeled, unlocked, unmarked_as_duplicate, unpinned, unsubscribed] but was user_blocked at path $.items[3].event 		at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:244) 		at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:213) 		at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127) 		at com.meisolsson.githubsdk.model.$AutoValue_IssueEvent$MoshiJsonAdapter.fromJson($AutoValue_IssueEvent.java:145) 		at com.meisolsson.githubsdk.model.$AutoValue_IssueEvent$MoshiJsonAdapter.fromJson($AutoValue_IssueEvent.java:29) 		at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127) 		at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:75) 		at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:52) 		at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127) 		at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:62) 		at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:20) 		at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127) 		at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:34) 		at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:42) 		at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:25) 		at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:118) 		at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:212) 		at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) 		at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41) 		at io.reactivex.Observable.subscribe(Observable.java:10700) 		at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) 		at io.reactivex.Single.subscribe(Single.java:2692) 		at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34) 		at io.reactivex.Observable.subscribe(Observable.java:10700) 		at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33) 		at io.reactivex.Observable.subscribe(Observable.java:10700) 		at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42) 		at io.reactivex.Observable.subscribe(Observable.java:10700) 		at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33) 		at io.reactivex.Observable.subscribe(Observable.java:10700) 		at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:223) 		at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onNext(ObservableConcatMap.java:130) 		at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246) 		at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:490) 		at io.reactivex.internal.util.AppendOnlyLinkedArrayList.forEachWhile(AppendOnlyLinkedArrayList.java:93) 		at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitLoop(BehaviorSubject.java:508) 		at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:455) 		at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:153) 		at io.reactivex.Observable.subscribe(Observable.java:10700) 		at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:52) 		at io.reactivex.Observable.subscribe(Observable.java:10700) 		at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58) 		at io.reactivex.Single.subscribe(Single.java:2692) 		at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33) 		at io.reactivex.Single.subscribe(Single.java:2692) 		at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33) 		at io.reactivex.Single.subscribe(Single.java:2692) 		at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33) 		at io.reactivex.Single.subscribe(Single.java:2692) 		at io.reactivex.internal.operators.single.SingleZipArray.subscribeActual(SingleZipArray.java:69) 		at io.reactivex.Single.subscribe(Single.java:2692) 		at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 		at io.reactivex.Scheduler$1.run(Scheduler.java:138) 		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59) 		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51) 		at java.util.concurrent.FutureTask.run(FutureTask.java:266) 		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 		at java.lang.Thread.run(Thread.java:919)
```

**Comment by KaKi87** [comment]
Also happening with https://github.com/duke7553/files-uwp/issues/37, any news on this ? Thanks
